-- TO HANDLE AUTH FOR USERS
CREATE TABLE USERS (
    USER_ID UUID PRIMARY KEY,
    USERNAME VARCHAR (100) UNIQUE NOT NULL,
    PASSWORD VARCHAR (255) NOT NULL,
    ROLE VARCHAR (20) NOT NULL CHECK ( ROLE IN ('PARENT', 'TEACHER'))
);

CREATE TABLE STUDENTS (
    ADMISSION_NUMBER VARCHAR (20) PRIMARY KEY,
    USER_ID UUID UNIQUE NOT NULL,
    FIRST_NAME VARCHAR (50) NOT NULL,
    MIDDLE_NAME VARCHAR (50),
    LAST_NAME VARCHAR (50) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE
);

CREATE TABLE SUBJECTS (
    SUBJECT_ID UUID PRIMARY KEY,
    SUBJECT_NAME VARCHAR (100) UNIQUE NOT NULL
);

CREATE TABLE GRADES (
    GRADE_ID UUID PRIMARY KEY,
    ADMISSION_NUMBER VARCHAR (20) NOT NULL,
    SUBJECT_ID UUID NOT NULL,
    ACADEMIC_YEAR INT NOT NULL,
    SCORE DECIMAL (5, 2) NOT NULL CHECK ( SCORE >= 0.00 AND SCORE <= 100.00 ),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ADMISSION_NUMBER) REFERENCES STUDENTS (ADMISSION_NUMBER) ON DELETE CASCADE,
    FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (SUBJECT_ID) ON DELETE CASCADE,
    CONSTRAINT UNIQUE_SUBJECT_STUDENT_YEAR UNIQUE (ADMISSION_NUMBER, SUBJECT_ID, ACADEMIC_YEAR)
);